### ISSUE TITLE
ngServe fails: Error in editor.api.d.ts

### ISSUE THREAD

**Issue by chedched** [materiahq/ngx-monaco-editor#21] opened 2019-12-21 14:46 UTC
I've installed the editor as described in detail in the readme file. When I'm now trying to run Angular with the CLI command "ng serve", I get an error:

```
ERROR in node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts(2167,44): error TS1005: ',' expected.
node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts(2167,54): error TS1005: ',' expected.
```

For testing purposes I set up an empty angular project, ngx-monaco-editor is the only installed component. Am I doing something wrong here or is this a bug?

**Comment by jmarc-roy** [comment] 2019-12-21 15:04
Probably duplicate of [#19](https://github.com/materiahq/ngx-monaco-editor/issues/19).

**Comment by chedched** [comment] 2019-12-21 20:37
Thank you very much for the super quick reaction!  #19 has been filed almost simultaneously, at the time I read through the issues it was not there yet. After downgrading the editor version I get another error:
`materia-ui-ngx-monaco-editor.js:234 Uncaught TypeError: Object(...) is not a function
    at materia-ui-ngx-monaco-editor.js:234
    at Module../node_modules/@materia-ui/ngx-monaco-editor/fesm5/materia-ui-ngx-monaco-editor.js (materia-ui-ngx-monaco-editor.js:236)`

Looks like this is something different though, so I guess this issue can be closed as well.

**Comment by jmarc-roy** [comment] 2019-12-22 20:34
Hi @chedched,
Do you still have an issue ?

**Closed as completed** 2019-12-29 14:19 UTC
